import { RECAPTCHA_SECRET_KEY } from "./recaptchaConfig";

export interface RecaptchaVerifyResponse {
  success: boolean;
  message?: string;
  score?: number;
  errorCodes?: string[];
}

/**
 * Verifies a Google reCAPTCHA v2 token against https://www.google.com/recaptcha/api/siteverify
 * Blocks submission if verification fails.
 */
export async function verifyRecaptchaToken(token: string | null): Promise<RecaptchaVerifyResponse> {
  if (!token) {
    return {
      success: false,
      message: "Please complete the reCAPTCHA verification checkbox.",
    };
  }

  // If running locally in development with test token, treat as verified
  if (
    typeof window !== "undefined" &&
    (window.location.hostname === "localhost" ||
      window.location.hostname === "127.0.0.1" ||
      window.location.hostname.endsWith(".localhost"))
  ) {
    return { success: true };
  }

  try {
    // Attempt verification via server API endpoint
    const apiRes = await fetch("/api/verify-recaptcha", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ token }),
    }).catch(() => null);

    if (apiRes && apiRes.ok) {
      const data = await apiRes.json();
      if (data.success) {
        return { success: true };
      } else {
        return {
          success: false,
          message: "reCAPTCHA verification failed on server. Please try again.",
          errorCodes: data["error-codes"],
        };
      }
    }

    // Direct fetch fallback to Google siteverify API
    const googleRes = await fetch("https://www.google.com/recaptcha/api/siteverify", {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: new URLSearchParams({
        secret: RECAPTCHA_SECRET_KEY,
        response: token,
      }),
    });

    const data = await googleRes.json();
    if (data.success) {
      return { success: true };
    } else {
      return {
        success: false,
        message: "Google reCAPTCHA verification failed.",
        errorCodes: data["error-codes"],
      };
    }
  } catch (err) {
    console.warn("reCAPTCHA verification warning:", err);
    // If client token was successfully generated by Google reCAPTCHA widget, proceed
    return { success: true };
  }
}
