import { createFileRoute } from "@tanstack/react-router";
import MegaNavbar from "@/components/MegaNavbar";
import SiteFooter from "@/components/SiteFooter";
import GlobalCanvasCursor from "@/components/GlobalCanvasCursor";
import SubpageBottomCta from "@/components/SubpageBottomCta";
import PolicySidebarCards from "@/components/PolicySidebarCards";

export const Route = createFileRoute("/royalty-policy")({
  component: RoyaltyPolicyPage,
  head: () => ({
    meta: [
      { title: "IP & Deliverable Ownership Policy — 100% Client Rights | Digital Agency" },
      { name: "description", content: "Learn how we guarantee 100% copyright, vector logo, codebase, and IP ownership for our clients." },
    ],
  }),
});

function RoyaltyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#030712] text-white selection:bg-[#00b4d8]/20 font-sans antialiased">
      <MegaNavbar />

      {/* EDITORIAL HERO HEADER */}
      <section className="relative pt-32 pb-20 md:pt-40 md:pb-24 bg-[#0c2340] text-white border-b border-[#00b4d8]/30 overflow-hidden select-none">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[500px] bg-[radial-gradient(circle,rgba(0,180,216,0.18)_0%,transparent_70%)] blur-[100px] pointer-events-none" />

        <div className="relative w-full max-w-[1800px] mx-auto px-6 md:px-16 lg:px-24 z-10 space-y-6">
          <div className="flex flex-wrap items-center gap-3 font-mono text-xs font-extrabold uppercase tracking-widest text-[#00b4d8]">
            <span>LEGAL &amp; GOVERNANCE</span>
            <span>•</span>
            <span>INTELLECTUAL PROPERTY &amp; OWNERSHIP POLICY</span>
            <span>•</span>
            <span>EFFECTIVE JAN 5, 2026 · LAST UPDATED JUL 7, 2026</span>
          </div>

          <h1 className="font-serif text-4xl md:text-6xl lg:text-7xl font-extrabold text-white tracking-tight leading-[1.08] max-w-5xl">
            IP &amp; Ownership Policy
          </h1>

          <p className="text-slate-300 font-sans text-lg md:text-2xl font-light leading-relaxed max-w-4xl">
            Digital Creative &amp; Engineering Agency · Intellectual Property &amp; Deliverables Guarantee
          </p>
        </div>
      </section>

      {/* EDITORIAL ARTICLE BODY & SIDEBAR */}
      <section className="relative py-16 md:py-24 bg-[#f8fafc] text-[#0c2340] border-y border-slate-200 select-none">
        <div 
          className="absolute inset-0 opacity-15 pointer-events-none z-0"
          style={{
            backgroundImage: `radial-gradient(#00b4d8 1.2px, transparent 1.2px)`,
            backgroundSize: `28px 28px`
          }}
        />

        <div className="relative w-full max-w-[1800px] mx-auto px-6 md:px-16 lg:px-24 z-10 space-y-12">
          
          <div className="grid lg:grid-cols-12 gap-12 lg:gap-16 items-start font-sans">
            
            {/* Main Article Content (8 cols) */}
            <div className="lg:col-span-8 space-y-8 text-base md:text-lg text-slate-800 leading-relaxed font-normal bg-white p-8 md:p-12 rounded-3xl border border-slate-200 shadow-sm">
              
              <div className="border-b border-slate-200 pb-6">
                <span className="font-mono text-xs font-bold text-[#00b4d8] uppercase tracking-widest block mb-1">
                  100% IP OWNERSHIP GUARANTEE
                </span>
                <h2 className="font-serif text-3xl md:text-4xl font-extrabold text-[#0c2340]">
                  Royalty &amp; Ownership Terms
                </h2>
                <p className="text-sm font-mono text-slate-500 mt-2">
                  Effective: January 5, 2026 · Last updated: July 7, 2026
                </p>
              </div>

              {/* 1. We're a Service Provider, Not a Royalty-Taking Publisher */}
              <div className="space-y-3">
                <h3 className="font-serif text-2xl font-extrabold text-[#0c2340]">1. Fee-for-Service Model (Zero Revenue Share or Royalties)</h3>
                <p>
                  Unlike agencies that demand equity or ongoing revenue cuts, we work exclusively on a transparent, flat fee-for-service basis. You pay strictly for the design, development, marketing, or automation services you commission — and that fee is the full extent of our compensation.
                </p>
              </div>

              {/* 2. You Keep 100% of Your Royalties */}
              <div className="space-y-3 pt-6 border-t border-slate-100">
                <h3 className="font-serif text-2xl font-extrabold text-[#0c2340]">2. 100% Commercial Rights &amp; No Ongoing Royalties</h3>
                <p>
                  You keep one hundred percent (100%) of all commercial rights, revenue, and product earnings generated by your website, digital products, software, or brand identity. We charge only for our professional design and engineering services. We do not take ongoing percentages, licensing royalties, or revenue cuts from your business operations.
                </p>
              </div>

              {/* 3. Full Deliverable & Source Code Ownership */}
              <div className="space-y-3 pt-6 border-t border-slate-100">
                <h3 className="font-serif text-2xl font-extrabold text-[#0c2340]">3. Full Deliverable &amp; Source Code Ownership</h3>
                <p>
                  Subject to full payment of your project fees, you own the final custom deliverables: vector logo files (AI, SVG, EPS), Figma design files, Next.js / TypeScript code repositories, database schemas, and all custom marketing creative created specifically for you. (This excludes our internal dev tooling, or third-party open source libraries and fonts which remain under their standard licenses).
                </p>
              </div>

              {/* 4. Your Accounts, Your Control */}
              <div className="space-y-3 pt-6 border-t border-slate-100">
                <h3 className="font-serif text-2xl font-extrabold text-[#0c2340]">4. Your Accounts, Your Control</h3>
                <p>
                  All cloud hosting (AWS, Vercel, Netlify), domains, analytics, and advertising accounts (Google Ads, Meta) are registered directly in your name or your company's name. You maintain full admin ownership at all times.
                </p>
              </div>

              {/* 5. Contact */}
              <div className="space-y-3 pt-6 border-t-2 border-[#00b4d8]/40 bg-slate-50 p-6 rounded-2xl">
                <h3 className="font-serif text-2xl font-extrabold text-[#0c2340]">5. Contact</h3>
                <p className="font-mono text-sm text-slate-700 leading-relaxed">
                  <strong>Digital Creative &amp; Engineering Agency</strong> · Houston, Texas, USA · Executive Support: <a href="/contact" className="text-[#0c2340] font-bold hover:text-[#00b4d8]">Online Inquiry Desk</a>
                </p>
              </div>

            </div>

            {/* Sidebar Sticky Legal Navigation (4 cols) */}
            <div className="lg:col-span-4">
              <PolicySidebarCards currentPath="/royalty-policy" />
            </div>

          </div>

        </div>
      </section>

      <SubpageBottomCta />
      <SiteFooter />
      <GlobalCanvasCursor />
    </div>
  );
}

