/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as AudiobookRouteImport } from './routes/audiobook'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoverDesignRouteImport } from './routes/cover-design'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as GhostwritingRouteImport } from './routes/ghostwriting'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LogoDesignRouteImport } from './routes/logo-design'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as NdaRouteImport } from './routes/nda'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RoyaltyPolicyRouteImport } from './routes/royalty-policy'
import { Route as SelfPublishingRouteImport } from './routes/self-publishing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestFormRouteImport } from './routes/test-form'
import { Route as WebsiteDesignRouteImport } from './routes/website-design'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiobookRoute = AudiobookRouteImport.update({
  id: '/audiobook',
  path: '/audiobook',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverDesignRoute = CoverDesignRouteImport.update({
  id: '/cover-design',
  path: '/cover-design',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostwritingRoute = GhostwritingRouteImport.update({
  id: '/ghostwriting',
  path: '/ghostwriting',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoDesignRoute = LogoDesignRouteImport.update({
  id: '/logo-design',
  path: '/logo-design',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const NdaRoute = NdaRouteImport.update({
  id: '/nda',
  path: '/nda',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyaltyPolicyRoute = RoyaltyPolicyRouteImport.update({
  id: '/royalty-policy',
  path: '/royalty-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfPublishingRoute = SelfPublishingRouteImport.update({
  id: '/self-publishing',
  path: '/self-publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFormRoute = TestFormRouteImport.update({
  id: '/test-form',
  path: '/test-form',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDesignRoute = WebsiteDesignRouteImport.update({
  id: '/website-design',
  path: '/website-design',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/audiobook': typeof AudiobookRoute
  '/contact': typeof ContactRoute
  '/cover-design': typeof CoverDesignRoute
  '/editing': typeof EditingRoute
  '/ghostwriting': typeof GhostwritingRoute
  '/landing': typeof LandingRoute
  '/location': typeof LocationRoute
  '/logo-design': typeof LogoDesignRoute
  '/marketing': typeof MarketingRoute
  '/nda': typeof NdaRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/royalty-policy': typeof RoyaltyPolicyRoute
  '/self-publishing': typeof SelfPublishingRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/test-form': typeof TestFormRoute
  '/website-design': typeof WebsiteDesignRoute
  '/work': typeof WorkRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/audiobook': typeof AudiobookRoute
  '/contact': typeof ContactRoute
  '/cover-design': typeof CoverDesignRoute
  '/editing': typeof EditingRoute
  '/ghostwriting': typeof GhostwritingRoute
  '/landing': typeof LandingRoute
  '/location': typeof LocationRoute
  '/logo-design': typeof LogoDesignRoute
  '/marketing': typeof MarketingRoute
  '/nda': typeof NdaRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/royalty-policy': typeof RoyaltyPolicyRoute
  '/self-publishing': typeof SelfPublishingRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/test-form': typeof TestFormRoute
  '/website-design': typeof WebsiteDesignRoute
  '/work': typeof WorkRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/audiobook': typeof AudiobookRoute
  '/contact': typeof ContactRoute
  '/cover-design': typeof CoverDesignRoute
  '/editing': typeof EditingRoute
  '/ghostwriting': typeof GhostwritingRoute
  '/landing': typeof LandingRoute
  '/location': typeof LocationRoute
  '/logo-design': typeof LogoDesignRoute
  '/marketing': typeof MarketingRoute
  '/nda': typeof NdaRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/royalty-policy': typeof RoyaltyPolicyRoute
  '/self-publishing': typeof SelfPublishingRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/test-form': typeof TestFormRoute
  '/website-design': typeof WebsiteDesignRoute
  '/work': typeof WorkRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-automation'
    | '/audiobook'
    | '/contact'
    | '/cover-design'
    | '/editing'
    | '/ghostwriting'
    | '/landing'
    | '/location'
    | '/logo-design'
    | '/marketing'
    | '/nda'
    | '/packages'
    | '/privacy'
    | '/process'
    | '/refund-policy'
    | '/royalty-policy'
    | '/self-publishing'
    | '/services'
    | '/terms'
    | '/test-form'
    | '/website-design'
    | '/work'
    | '/service/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-automation'
    | '/audiobook'
    | '/contact'
    | '/cover-design'
    | '/editing'
    | '/ghostwriting'
    | '/landing'
    | '/location'
    | '/logo-design'
    | '/marketing'
    | '/nda'
    | '/packages'
    | '/privacy'
    | '/process'
    | '/refund-policy'
    | '/royalty-policy'
    | '/self-publishing'
    | '/services'
    | '/terms'
    | '/test-form'
    | '/website-design'
    | '/work'
    | '/service/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-automation'
    | '/audiobook'
    | '/contact'
    | '/cover-design'
    | '/editing'
    | '/ghostwriting'
    | '/landing'
    | '/location'
    | '/logo-design'
    | '/marketing'
    | '/nda'
    | '/packages'
    | '/privacy'
    | '/process'
    | '/refund-policy'
    | '/royalty-policy'
    | '/self-publishing'
    | '/services'
    | '/terms'
    | '/test-form'
    | '/website-design'
    | '/work'
    | '/service/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAutomationRoute: typeof AiAutomationRoute
  AudiobookRoute: typeof AudiobookRoute
  ContactRoute: typeof ContactRoute
  CoverDesignRoute: typeof CoverDesignRoute
  EditingRoute: typeof EditingRoute
  GhostwritingRoute: typeof GhostwritingRoute
  LandingRoute: typeof LandingRoute
  LocationRoute: typeof LocationRoute
  LogoDesignRoute: typeof LogoDesignRoute
  MarketingRoute: typeof MarketingRoute
  NdaRoute: typeof NdaRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RoyaltyPolicyRoute: typeof RoyaltyPolicyRoute
  SelfPublishingRoute: typeof SelfPublishingRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  TestFormRoute: typeof TestFormRoute
  WebsiteDesignRoute: typeof WebsiteDesignRoute
  WorkRoute: typeof WorkRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiobook': {
      id: '/audiobook'
      path: '/audiobook'
      fullPath: '/audiobook'
      preLoaderRoute: typeof AudiobookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-design': {
      id: '/cover-design'
      path: '/cover-design'
      fullPath: '/cover-design'
      preLoaderRoute: typeof CoverDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghostwriting': {
      id: '/ghostwriting'
      path: '/ghostwriting'
      fullPath: '/ghostwriting'
      preLoaderRoute: typeof GhostwritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-design': {
      id: '/logo-design'
      path: '/logo-design'
      fullPath: '/logo-design'
      preLoaderRoute: typeof LogoDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nda': {
      id: '/nda'
      path: '/nda'
      fullPath: '/nda'
      preLoaderRoute: typeof NdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royalty-policy': {
      id: '/royalty-policy'
      path: '/royalty-policy'
      fullPath: '/royalty-policy'
      preLoaderRoute: typeof RoyaltyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-publishing': {
      id: '/self-publishing'
      path: '/self-publishing'
      fullPath: '/self-publishing'
      preLoaderRoute: typeof SelfPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-form': {
      id: '/test-form'
      path: '/test-form'
      fullPath: '/test-form'
      preLoaderRoute: typeof TestFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-design': {
      id: '/website-design'
      path: '/website-design'
      fullPath: '/website-design'
      preLoaderRoute: typeof WebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAutomationRoute: AiAutomationRoute,
  AudiobookRoute: AudiobookRoute,
  ContactRoute: ContactRoute,
  CoverDesignRoute: CoverDesignRoute,
  EditingRoute: EditingRoute,
  GhostwritingRoute: GhostwritingRoute,
  LandingRoute: LandingRoute,
  LocationRoute: LocationRoute,
  LogoDesignRoute: LogoDesignRoute,
  MarketingRoute: MarketingRoute,
  NdaRoute: NdaRoute,
  PackagesRoute: PackagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RoyaltyPolicyRoute: RoyaltyPolicyRoute,
  SelfPublishingRoute: SelfPublishingRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  TestFormRoute: TestFormRoute,
  WebsiteDesignRoute: WebsiteDesignRoute,
  WorkRoute: WorkRoute,
  ServiceSlugRoute: ServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
